[project]
name = "usl-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "loguru>=0.7.3",
    "praw>=7.8.1",
    "pydantic-settings>=2.11.0",
    "uvicorn[standard]>=0.38.0",
]
